export const sku_db = [{
	"Sub SKU ID": "7125620",
	"Name": "A)FRONTLINE PLUS CAT x1",
	"Subs Price": "£5.50",
	"Annual Sub Cost": "£66.00",
	"Prod Link": "https://www.petsathome.com/shop/en/pets/frontline-plus-subscribe-and-save-p50001?pettype=cat&petweight=0+-+10kg",
	"One-Time SKU ID": "18364",
	"Pack Price": "£19.50",
	"Annual": "£78.00",
	"Save": "£12.00",
	"Save %": "15%",
	"Online product link": "https://www.petsathome.com/shop/en/pets/frontline-plus-3-spot-on-flea-and-tick-pipettes-cat-up-to-10kg"
}, {
	"Sub SKU ID": "7125619",
	"Name": "A)FRONTLINE PLUS DOG S x1",
	"Subs Price": "£7.00",
	"Annual Sub Cost": "£84.00",
	"Prod Link": "https://www.petsathome.com/shop/en/pets/frontline-plus-subscribe-and-save-p50001?pettype=dog&petweight=2+-+10kg",
	"One-Time SKU ID": "18360",
	"Pack Price": "£27.50",
	"Annual": "£110.00",
	"Save": "£26.00",
	"Save %": "24%",
	"Online product link": "https://www.petsathome.com/shop/en/pets/frontline-plus-3-spot-on-flea-and-tick-pipettes-small-dog-puppy-2-10kg"
}, {
	"Sub SKU ID": "7125621",
	"Name": "A)FRONTLINE PLUS DOG M x1",
	"Subs Price": "£7.00",
	"Annual Sub Cost": "£84.00",
	"Prod Link": "https://www.petsathome.com/shop/en/pets/frontline-plus-subscribe-and-save-p50001?pettype=dog&petweight=10.01+-+20kg",
	"One-Time SKU ID": "18361",
	"Pack Price": "£28.50",
	"Annual": "£114.00",
	"Save": "£30.00",
	"Save %": "26%",
	"Online product link": "https://www.petsathome.com/shop/en/pets/frontline-plus-3-spot-on-flea-and-tick-pipettes-medium-dog-puppy-10-20kg"
}, {
	"Sub SKU ID": "7125622",
	"Name": "A)FRONTLINE PLUS DOG L x1",
	"Subs Price": "£8.00",
	"Annual Sub Cost": "£96.00",
	"Prod Link": "https://www.petsathome.com/shop/en/pets/frontline-plus-subscribe-and-save-p50001?pettype=dog&petweight=20.01+-+40kg",
	"One-Time SKU ID": "18362",
	"Pack Price": "£33.00",
	"Annual": "£132.00",
	"Save": "£36.00",
	"Save %": "27%",
	"Online product link": "https://www.petsathome.com/shop/en/pets/frontline-plus-3-spot-on-flea-and-tick-pipettes-large-dog-puppy-20-40kg"
}, {
	"Sub SKU ID": "7125623",
	"Name": "L)FRONTLINE PLUS DOG XL x1",
	"Subs Price": "£8.00",
	"Annual Sub Cost": "£96.00",
	"Prod Link": "https://www.petsathome.com/shop/en/pets/frontline-plus-subscribe-and-save-p50001?pettype=dog&petweight=40.01kg+and+over",
	"One-Time SKU ID": "19620",
	"Pack Price": "£38.00",
	"Annual": "£152.00",
	"Save": "£56.00",
	"Save %": "37%",
	"Online product link": "https://www.petsathome.com/shop/en/pets/frontline-plus-3-spot-on-flea-and-tick-pipettes-extra-large-dog-40-60kg"
}, {
	"Sub SKU ID": "7120049",
	"Name": "A)ADVANTAGE 40 CAT X 1",
	"Subs Price": "£4.00",
	"Annual Sub Cost": "£48.00",
	"Prod Link": "https://www.petsathome.com/shop/en/pets/advantage-spot-on-cat-and-dog-flea-treatment-%C2%A0%28monthly-subscription-service%29-p50000?pettype=cat&petweight=0+-+3.99kg",
	"One-Time SKU ID": "32291",
	"Pack Price": "£20.50",
	"Annual": "£61.50",
	"Save": "£13.50",
	"Save %": "22%",
	"Online product link": "https://www.petsathome.com/shop/en/pets/advantage-40-spot-on-solution-for-small-cats-small-dogs-and-pet-rabbits"
}, {
	"Sub SKU ID": "7120050",
	"Name": "A)ADVANTAGE 80 CAT x 1",
	"Subs Price": "£4.00",
	"Annual Sub Cost": "£48.00",
	"Prod Link": "https://www.petsathome.com/shop/en/pets/advantage-spot-on-cat-and-dog-flea-treatment-%C2%A0%28monthly-subscription-service%29-p50000?pettype=cat&petweight=4kg+and+over",
	"One-Time SKU ID": "32292",
	"Pack Price": "£21.50",
	"Annual": "£64.50",
	"Save": "£16.50",
	"Save %": "26%",
	"Online product link": "https://www.petsathome.com/shop/en/pets/advantage-80-spot-on-solution-for-large-cats-and-pet-rabbits"
}, {
	"Sub SKU ID": "7120051",
	"Name": "A)ADVANTAGE 100 DOG x 1",
	"Subs Price": "£4.50",
	"Annual Sub Cost": "£54.00",
	"Prod Link": "https://www.petsathome.com/shop/en/pets/advantage-spot-on-cat-and-dog-flea-treatment-%C2%A0%28monthly-subscription-service%29-p50000?pettype=dog&petweight=4+-+9.99kg",
	"One-Time SKU ID": "32293",
	"Pack Price": "£22.50",
	"Annual": "£67.50",
	"Save": "£13.50",
	"Save %": "20%",
	"Online product link": "https://www.petsathome.com/shop/en/pets/advantage-spot-on-solution-for-dogs?size=dogs+4-10kg"
}, {
	"Sub SKU ID": "7120052",
	"Name": "A)ADVANTAGE 250 DOG x 1",
	"Subs Price": "£4.50",
	"Annual Sub Cost": "£54.00",
	"Prod Link": "https://www.petsathome.com/shop/en/pets/advantage-spot-on-cat-and-dog-flea-treatment-%C2%A0%28monthly-subscription-service%29-p50000?pettype=dog&petweight=10+-+24.99kg",
	"One-Time SKU ID": "32294",
	"Pack Price": "£23.50",
	"Annual": "£70.50",
	"Save": "£16.50",
	"Save %": "23%",
	"Online product link": "https://www.petsathome.com/shop/en/pets/advantage-spot-on-solution-for-dogs?size=dogs+10-25kg"
}, {
	"Sub SKU ID": "7120053",
	"Name": "L)ADVANTAGE 400 DOG x 1",
	"Subs Price": "£4.50",
	"Annual Sub Cost": "£54.00",
	"Prod Link": "https://www.petsathome.com/shop/en/pets/advantage-spot-on-cat-and-dog-flea-treatment-%C2%A0%28monthly-subscription-service%29-p50000?pettype=dog&petweight=25+-+39.99kg",
	"One-Time SKU ID": "32295",
	"Pack Price": "£24.50",
	"Annual": "£73.50",
	"Save": "£19.50",
	"Save %": "27%",
	"Online product link": "https://www.petsathome.com/shop/en/pets/advantage-spot-on-solution-for-dogs?size=dogs+25kg%2B"
}, {
	"Sub SKU ID": "7134143",
	"Name": "L)Dronspot Small Cat Sub ",
	"Subs Price": "£6.00",
	"Annual Sub Cost": "£72.00",
	"Prod Link": "https://www.petsathome.com/shop/en/pets/dronspot-spot-on-wormer-for-cats-p50003?pettype=cat&petweight=0.5kg+-+2.50kg",
	"One-Time SKU ID": "not available",
	"Pack Price": "£8.50",
	"Annual": "£51.00",
	"Save": "£18.00",
	"Save %": "20%",
	"Online product link": ""
}, {
	"Sub SKU ID": "7134144",
	"Name": "L)Dronspot Med Cat Sub ",
	"Subs Price": "£6.00",
	"Annual Sub Cost": "£72.00",
	"Prod Link": "https://www.petsathome.com/shop/en/pets/dronspot-spot-on-wormer-for-cats-p50003?pettype=cat&petweight=2.51kg+-+5.00kg",
	"One-Time SKU ID": "not available",
	"Pack Price": "£15.00",
	"Annual": "£90.00",
	"Save": "£18.00",
	"Save %": "20%",
	"Online product link": ""
}, {
	"Sub SKU ID": "7134145",
	"Name": "L)Dronspot Large Cat Sub ",
	"Subs Price": "£6.00",
	"Annual Sub Cost": "£72.00",
	"Prod Link": "https://www.petsathome.com/shop/en/pets/dronspot-spot-on-wormer-for-cats-p50003?pettype=cat&petweight=5.01kg+-+8.00kg",
	"One-Time SKU ID": " 7131981",
	"Pack Price": "£15.00",
	"Annual": "£90.00",
	"Save": "£18.00",
	"Save %": "20%",
	"Online product link": "https://www.petsathome.com/shop/en/pets/dronspot-spot-on-large-cat-wormer-pack-2"
}, {
	"Sub SKU ID": "7136712",
	"Name": "L)DrontalTasty Sub 2-10kg ",
	"Subs Price": "£3.50",
	"Annual Sub Cost": "£42.00",
	"Prod Link": "https://www.petsathome.com/shop/en/pets/drontal-worming-treatment-for-dogs-%28monthly-subscription-service%29-p50008?pettype=dog&petweight=2+-+10kg",
	"One-Time SKU ID": "33881 (2 pack)",
	"Pack Price": "£31.00",
	"Annual": "£62.00",
	"Save": "£20.00",
	"Save %": "32%",
	"Online product link": "https://www.petsathome.com/shop/en/pets/drontal-flavour-plus-bone-shaped-worming-tablet-for-dogs"
}, {
	"Sub SKU ID": "7136714",
	"Name": "L)DrontalTastySub 10.01-17kg ",
	"Subs Price": "£5.50",
	"Annual Sub Cost": "£66.00",
	"Prod Link": "https://www.petsathome.com/shop/en/pets/drontal-worming-treatment-for-dogs-%28monthly-subscription-service%29-p50008?pettype=dog&petweight=10.01+-+17.5kg",
	"One-Time SKU ID": "33882 (6 pack)",
	"Pack Price": "£31.00",
	"Annual": "£124.00",
	"Save": "£58.00",
	"Save %": "47%",
	"Online product link": "https://www.petsathome.com/shop/en/pets/drontal-flavour-plus-bone-shaped-worming-tablet-for-dogs"
}, {
	"Sub SKU ID": "7136715",
	"Name": "L)Drontal XL Sub 17.51-35kg ",
	"Subs Price": "£6.50",
	"Annual Sub Cost": "£78.00",
	"Prod Link": "https://www.petsathome.com/shop/en/pets/drontal-worming-treatment-for-dogs-%28monthly-subscription-service%29-p50008?pettype=dog&petweight=17.51+-+35kg",
	"One-Time SKU ID": "7129998",
	"Pack Price": "£21.00",
	"Annual": "£126.00",
	"Save": "£48.00",
	"Save %": "38%",
	"Online product link": "https://www.petsathome.com/shop/en/pets/drontal-dog-tasty-bone-xl-worming-tablets-2-pack-%28home-delivery%29"
}]

export default sku_db